---
name: cs580s2020_project-proposal
break: true
fastfail: false
indent: 4
---
src/preamble:
    bibliography.bib:
        ConfirmFileExists
        MatchFileFragment --fragment "@article" --count 1
        MatchFileFragment --fragment "@inproceedings" --count 1
        MatchFileFragment --fragment "dasgupta2015comrade" --count 0 --exact
    mydefinitions.tex:
        ConfirmFileExists
        MatchFileFragment --fragment "Janyl Jumadinova" --count 0 --exact
        MatchFileFragment --fragment "Proposal Title" --count 0 --exact
src:
    SeniorThesisProposal.tex:
        # CountFileWords --count 1100
        ConfirmFileExists
        MatchFileFragment --fragment "input{preamble/mydefinitions}" --count 1 --exact
CountCommits --count 10
