---
name: cs580s2020_lab01
break: true
fastfail: false
indent: 4
---
src/preamble:
    bibliography.bib:
        ConfirmFileExists
        MatchFileFragment --fragment "@article" --count 1
        MatchFileFragment --fragment "@inproceedings" --count 1
        MatchFileFragment --fragment "dasgupta2015comrade" --count 0 --exact
    mydefinitions.tex:
        ConfirmFileExists
        MatchFileFragment --fragment "Janyl Jumadinova" --count 0 --exact
        MatchFileFragment --fragment "Proposal Title" --count 0 --exact
src:
    SeniorThesisProposal.tex:
        CountFileWords --count 1100
        ConfirmFileExists
        MatchFileFragment --fragment "input{preamble/mydefinitions}" --count 1 --exact
        MatchFileFragment --fragment "section" --count 6
        MatchFileFragment --fragment "bibliography{preamble/bibliography}" --count 1 --exact
        MatchFileFragment --fragment "includegraphics" --count 2
        MatchFileFragment --fragment "begin{itemize}" --count 1
        MatchFileFragment --fragment "end{itemize}" --count 1
        MatchFileFragment --fragment "begin{enumerate}" --count 1
        MatchFileFragment --fragment "end{enumerate}" --count 1
        MatchFileFragment --fragment "begin{verbatim}" --count 1
        MatchFileFragment --fragment "end{verbatim}" --count 1
        MatchFileFragment --fragment "textbf{" --count 1
        MatchFileFragment --fragment "emph{" --count 1
CountCommits --count 1
